import './globals.css';

import { Header } from '@/components';
import { Inter } from 'next/font/google';
import Loading from './loading';
import type { Metadata } from 'next';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Refer App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <Header />
          <main>{children}</main>
        </Suspense>
      </body>
    </html>
  );
}
